---
title: "Data_automatization_HW"
author: "Shakir Suleimanov"
date: '2022-11-02'
output:
  word_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

Загрузим необходимые библиотеки

```{r}
library(tidyverse)
library(readxl)
library(flextable)
library(gtsummary)
```

Загрузим данные и посмиотрим на их структуру

```{r}
data <- read_excel("data_excel.xlsx")
str(data)
```

Преобразуем наши данные для более удобной работы

```{r}
data <- data %>%
  mutate_at(vars(contains("E")), ~ gsub(",", ".", .) %>% as.numeric()) %>%
  mutate(`Группа` = as.factor(`Группа`)) %>%
  mutate(`Пол` = as.factor(`Пол`)) %>%
  mutate_at(vars(contains("E")), ~ ifelse(. <= 0, NA, .))

data
```

Создадим лист со статистиками, как на stepik

```{r}
statistics <- list(
      `_Количество субъектов` = ~length(.x) %>% as.character(),
      `_Количество (есть данные)` = ~sum(!is.na(.x)) %>% as.character(),
      `_Нет данных` = ~sum(is.na(.x)) %>% as.character(),
      `_Ср. знач.` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", mean(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `_Станд. отклон.` = ~ifelse(sum(!is.na(.x)) < 3, "Н/П*", sd(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `_95% ДИ для среднего` = ~sd(.x, na.rm = TRUE) %>% round(2) %>% as.character(),
      `_мин. - макс.` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", paste0(min(.x, na.rm = TRUE) %>% round(2), " - ", max(.x, na.rm = TRUE) %>% round(2))),
      `_Медиана` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", median(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
      `_Q1 - Q3` = ~ifelse(sum(!is.na(.x)) == 0, "Н/П*", paste0(quantile(.x, 0.25, na.rm = TRUE) %>% round(2), " - ", quantile(.x, 0.75, na.rm = TRUE) %>% round(2)))
)
```


Сделаем таблицу для номинативных переменных

```{r}

data %>%
  select(`Группа`, where(is.numeric)) %>%
  group_by(`Группа`) %>%
  summarise(across(where(is.numeric), statistics)) %>%
  pivot_longer(!`Группа`) %>%
  separate(name, c("Переменная", "Статистика"), sep = "__") %>%
  rename(`Значение` = value) %>%
  flextable() %>%
  theme_box() %>%
  merge_v(c("Группа", "Переменная"))

```

Сделаем таблицу для неноминативных переменных

```{r}
data %>% 
  select(`Группа`, where(is.character)) %>%
  mutate(`Группа крови` = `Группа крови` %>% replace_na("Нет данных") %>% as.factor()) %>%
  count(`Группа`, `Группа крови`) %>%
  group_by(`Группа`) %>%
  mutate(`Процент по группе` = (n / sum(n)) %>% round(4) %>% '*'(100) %>% str_c("%")) %>%
  ungroup() %>%
  mutate(`Процент по выборке` = (n / sum(n)) %>% round(4) %>% '*'(100) %>% str_c("%")) %>%
  flextable() %>%
  theme_box() %>%
  merge_v("Группа") 
```

Статистическая описательная таблица (table 1)

```{r}
data %>%
  tbl_summary(by = `Группа`, missing = "no") %>%
  add_p()
```




